### ISSUE TITLE
BaseUrl is Required

### ISSUE THREAD

**Issue by Astha1298** [cmfcmf/docusaurus-search-local#111]
### Please describe the bug you are seeing

I used the Installation and ran the command. 
Later added code to Config.js file. 

While running npm run start 
Getting [ERROR] Error: "baseUrl" is required
"title" is required
"url" is required

But I already have defined baseUrl and title and url to my Config = {};

### Which Node.js version are you using?

v16.13.0

### Which theme are you using?

Yes, I am using @docusaurus/theme-classic

### How does your plugin config look like?

[cmfcmf](https://github.com/cmfcmf)
/
[docusaurus-search-local](https://github.com/cmfcmf/docusaurus-search-local)

**Comment by cmfcmf** [comment]
Hi! I don't think this issue is related to this plugin. Feel free to post your `docusaurus.config.js` file though, then I might be able to help you find the issue.
