### ISSUE TITLE
This page crashed.

### ISSUE THREAD

**Issue by hijulien** [cmfcmf/docusaurus-search-local#118]
### Please describe the bug you are seeing

This happens when I install it and run it again
![image](https://user-images.githubusercontent.com/103170141/170297151-7752164e-920f-4f85-9e92-72fa1e7c56b4.png)

### Which Node.js version are you using?

16

### Which theme are you using?

Yes, I am using @docusaurus/theme-classic

### How does your plugin config look like?

plugins: [
    [
      require.resolve("@cmfcmf/docusaurus-search-local"),
      {
        indexDocs: true,
        indexDocSidebarParentCategories: 0,
        indexBlog: true,
        indexPages: false,
        language: "zh",
        style: undefined,
        lunr: {
          tokenizerSeparator: /[\s\-]+/,
          b: 0.75,
          k1: 1.2,
          titleBoost: 5,
          contentBoost: 1,
          parentCategoriesBoost: 2,
        }
      },
    ],
  ],

**Comment by cmfcmf** [comment]
Hmm, I am not sure whether this error is caused by this plugin. If it occurrs again, could you please provide stacktraces from devtools?
