### ISSUE TITLE
RTL support 

### ISSUE THREAD

**Issue by georgettica** [cmfcmf/docusaurus-search-local#119]
:unicorn:

I am not sure if it's OOTB, but I want to translate to a language that needs to override the RTL.

Should this be in the json file? Or should I just have a set of languages in an array so we can check `shouldRTL`

Posting as I might use it for personal uses and wanted to discuss before implementing

**Comment by cmfcmf** [comment]
Hi, since Docusaurus has [RTL support](https://docusaurus.io/docs/i18n/introduction), I would expect things to mostly "just work". But please let me know if you run into any issues!

**Comment by georgettica** [comment]
I'll add it as is and check how it'll go..

Thanks!
