### ISSUE TITLE
when i seted "language: ['ja']" and build ,An error has occurred related lunr

### ISSUE THREAD

**Issue by shigeru-sakurai** [cmfcmf/docusaurus-search-local#12]
## Problem

when i build project After seted `docusaurus.config.js` as follows

```javascript
  plugins: [
    [
      require.resolve('@cmfcmf/docusaurus-search-local'),
      {
        language: ['ja'],
      },
    ],
  ],
```

An error has occurred related lunr

```shell
TypeError: lunr.TinySegmenter is not a constructor
   at /home/user/project/node_modules/lunr-languages/lunr.ja.js:88:21
```

## Guess about revision

I looked around `node_modules/lunr-languages/lunr.ja.js` and finded `tinyseg.js` so Made it read it.
build is done and i could search word with japanese.

- lunr.ja.js
```javascript
require('./tinyseg.js')(lunr) // + add
var segmenter = new lunr.TinySegmenter() // インスタンス生成
```

Sorry if my English is weird.

**Comment by cmfcmf** [comment]
Thank you for bringing this up! It should be fixed in https://github.com/cmfcmf/docusaurus-search-local/commit/871cca9635a6fcd4d829c7b9916d038e5aacd97d. I released version 0.3.0 that includes this fix.
