### ISSUE TITLE
Change the styling of the search box

### ISSUE THREAD

**Issue by Asik007** [cmfcmf/docusaurus-search-local#120]
:unicorn:
This is one of my first webpage project and don't really know much about css and js. I thought I could simply override the themes css by defining the css variables in my own file. That didn't work and now im lost. My site is published [here](asik007.github.io/my-website/). the repo is [here](https://github.com/Asik007/my-website/tree/uhhh-not-broken).
pls help
Thank you!

**Comment by cmfcmf** [comment]
Hey, take a look at #107. One important thing is that you have to use `!important` when overwriting the CSS variables. Let me know if that works!

**Comment by Asik007** [comment]
It works!!! Thank you for showing me that issue. I probably should have looked around more, sorry.
