### ISSUE TITLE
Can we index frontmatter tags?

### ISSUE THREAD

**Issue by gentledepp** [cmfcmf/docusaurus-search-local#121]
:unicorn:

Hello! 
I am currently playing around with local search and found, that frontmatter tags are not indexed.
Is there any possibility to configure this?

For example, in an MDX like the following, i would like to be able to find this page by searching for e.g. `coordinator`

```
---
title: Upgrading a workbook
tags: 
  - coordinator
  - updating
  - designer
  - upgrading
---
```

Thank you!

**Comment by cmfcmf** [comment]
Good point! Implemented in https://github.com/cmfcmf/docusaurus-search-local/commit/df0a81ee07c84f15c8d0095e31aa827a45289c19.
