### ISSUE TITLE
"v" in peerDependency for docusaurus

### ISSUE THREAD

**Issue by dkershner6** [cmfcmf/docusaurus-search-local#124]
### Please describe the bug you are seeing

There are no versions that dont violate the peerDependency, because I believe it is invalid (due to having a preceding "v"):
https://github.com/cmfcmf/docusaurus-search-local/blob/9d309412b4442e38f56758cd7b4d255089706f5d/packages/docusaurus-search-local/package.json#L37

### How can we best reproduce the bug?

Just installing works for me.

### Which version of Docusaurus and @cmfcmf/docusaurus-search-local are you using?

2.0.0-beta21
latest

### Which Node.js version are you using?

16.15.0

### Which theme are you using?

Yes, I am using @docusaurus/theme-classic

### How does your plugin config look like?

Not relevant to this bug

### Additional context

Nope

**Comment by cmfcmf** [comment]
Thanks for letting me know! Should b e fixed in https://github.com/cmfcmf/docusaurus-search-local/commit/f8619b72ec748ac084b53cf7c88157419a27863a.
