### ISSUE TITLE
Support Docusaurus 2.0 stable

### ISSUE THREAD

**Issue by Fannon** [cmfcmf/docusaurus-search-local#131]
Docusaurus 2 is out 🎆 !
https://docusaurus.io/blog/2022/08/01/announcing-docusaurus-2.0

The current version of this plugin still has an outdated peer dependency:

```text
npm ERR! Conflicting peer dependency: @docusaurus/core@2.0.1
npm ERR! node_modules/@docusaurus/core
npm ERR!   peer @docusaurus/core@"^v2.0.0-beta.21" from @cmfcmf/docusaurus-search-local@0.11.0
npm ERR!   node_modules/@cmfcmf/docusaurus-search-local
npm ERR!     @cmfcmf/docusaurus-search-local@"0.11.0" from the root project
```

It can be force installed via 

```sh
npm i --legacy-peer-deps
```

But when trying this quicky, I'm not sure if it worked, the search index couldn't be found even after running a build. So maybe some additional work needs to be done to get it on 2.0 officially.

Thanks for working on this plugin, it's really helpful!

**Comment by noraj** [comment]
In docusaurus v2.1.0 the search bar doesn't display even when having this navbar item:

```js
        {
          type: 'search',
          position: 'right',
        }
```

**Comment by cmfcmf** [comment]
I finally added support for Docusaurus v2 in https://github.com/cmfcmf/docusaurus-search-local/commit/f8619b72ec748ac084b53cf7c88157419a27863a.
