### ISSUE TITLE
How to show page title in search results?

### ISSUE THREAD

**Issue by rethab** [cmfcmf/docusaurus-search-local#134]
Hi, when searching e.g. `api` on your sample page, it shows "Getting Started" below "Installation":

![image](https://user-images.githubusercontent.com/2222044/185329615-493a7365-93c8-4f02-8bd8-77ea8d3134e2.png)

I think this would be very helpful for terms that exist on various pages. Based on what does the plugin decide to show the page name? Is there a way to make this plugin always show the page? 

Perhaps the above is a poor example, as the first few results seem to be page titles, which means showing the page title would be redundant. However, in my sample docusaurus installation (which I can't show unfortunately), I have e.g. the term "Crypto" on various pages as a subtitle `## Crypto`. If I then search for "Crypto" it shows "Crypto" as a result without additional context on which page it was found.

**Comment by stephendpmurphy** [comment]
I second this! Something to give the searcher more context into each "result" would be great.

**Comment by tiltos** [comment]
This looks like it's a core feature. How can we go about turning it on?
![image](https://user-images.githubusercontent.com/259111/210563989-e3f8b826-a6b9-4050-8834-7a65e7a84108.png)

**Comment by stephendpmurphy** [comment]
@tiltos I was hoping to find some config on their Github but there's nothing beyond adding the plugin in the docusaurus config. They are using an older version (0.9.3) so maybe it was a feature that was enabled and then turned off in later versions?

**Comment by stephendpmurphy** [comment]
@rethab @tiltos Ah, after further testing it only appears to work if you place custom config and build out the sidebar manually. The feature doesn't appear to work if you use the auto-generated sidebar.

**Comment by cmfcmf** [comment]
Sorry for the long delay!
This was broken for a bit, but should be fixed in the next version (see https://github.com/cmfcmf/docusaurus-search-local/issues/146).
