### ISSUE TITLE
"Error: EROFS: read-only filesystem" when using Yarn PnP

### ISSUE THREAD

**Issue by onox** [cmfcmf/docusaurus-search-local#139]
### Please describe the bug you are seeing

`yarn build` fails with the following error:

```
[INFO] [en] Creating an optimized production build...
[ERROR] Unable to build website for locale en.
[ERROR] Error: EROFS: read-only filesystem, open '/node_modules/@cmfcmf/docusaurus-search-local/src/client/theme/SearchBar/generated.js'
```

### How can we best reproduce the bug?

I think this occurs when using PnP because packages become .zip files in .yarn/cache/.

### Which version of Docusaurus and @cmfcmf/docusaurus-search-local are you using?

From `yarn info`:

@docusaurus/core@npm:2.1.0
@cmfcmf/docusaurus-search-local@npm:0.11.0

### Which Node.js version are you using?

v18.7.0

### Which theme are you using?

Yes, I am using @docusaurus/theme-classic

### Additional context

Allow the user to configure the folder in which generated files are stored.

**Comment by BowlingX** [comment]
Workaround:
Use `yarn unplug @cmfcmf/docusaurus-search-local` to solve the problem temporary.
