### ISSUE TITLE
Feature Request: Ability to config the CSS selector for page titles

### ISSUE THREAD

**Issue by chszchen-nordcloud** [cmfcmf/docusaurus-search-local#144]
Currently the plugin looks for `pageTitle` with a hardcoded CSS selector [here](https://github.com/cmfcmf/docusaurus-search-local/blob/9d309412b4442e38f56758cd7b4d255089706f5d/packages/docusaurus-search-local/src/server/parse.ts#L100) in `parse.ts`, while building index files. However, we've come across cases where this selector did not match the desired text and page titles were left empty during searching. Since the HTML documents are generated from MDX files automatically by `docusaurus`, we do not have direct control over the structure of the generated document. It would be much more flexible if the CSS selector used for extracting `pageTitle` could be configurable.

**Comment by cmfcmf** [comment]
Hey, I think title extraction is fixed (see https://github.com/cmfcmf/docusaurus-search-local/issues/146). I'll release a new version this weekend.
