### ISSUE TITLE
Need to add one more installation step

### ISSUE THREAD

**Issue by ivancheban** [cmfcmf/docusaurus-search-local#15]
:unicorn:
After you install this npm package, you need to `npm install` before building your project with `npm run build`.

**Comment by cmfcmf** [comment]
Hi @ivancheban,
I'm not 100% sure I can follow what you mean.The Readme says that you first need to `npm install @cmfcmf/docusaurus-search-local` and then can run `npm run build`. Are you suggesting to run `npm install` in between these two commands? I don't think that's necessary.

**Comment by ivancheban** [comment]
![image](https://user-images.githubusercontent.com/47241364/89865763-fe961180-dbb6-11ea-819a-8c5fd649a0ba.png)
The readme Installation section says that you need to `npm install @cmfcmf/docusaurus-search-local`, that's all. The second step should be `npm install`. Otherwise, if you execute `npm run build', you'll get an error.

**Comment by ivancheban** [comment]
To install docusaurus-search-local:
1. Go to your root folder.
2. `yarn add @cmfcmf/docusaurus-search-local` or `npm install @cmfcmf/docusaurus-search-local`.
3. `npm install`.
4. `npm run build'.

**Comment by cmfcmf** [comment]
I'm sorry, I still can't reproduce your issue. I tried the following commands to setup a new installation and everything worked without an issue:
```bash
npx @docusaurus/init@next init my-website classic
yarn add @cmfcmf/docusaurus-search-local
cd my-website
vim docusuaurus.config.js # add plugin to config
yarn start
```
