### ISSUE TITLE
how to enable search in localhost?

### ISSUE THREAD

**Issue by sibelius** [cmfcmf/docusaurus-search-local#159]
:unicorn:

I've read all these

```
You can now use the search bar to search your documentation.

Important: Search only works for the statically built documentation (i.e., after you ran yarn build in your documentation folder).

Search does not work in development (i.e., when running yarn start). If you want to test search locally, first build the documentation with yarn build, and then serve it via yarn serve.
```

but how can I generate search index even locally?

Can I have a nodemon/watch command running in the background ?

**Comment by cmfcmf** [comment]
Unfortunately, the only way to have working search on locally is to build the documentation (`docusaurus build`) and then serve the documentation (`docusaurus serve`).
