### ISSUE TITLE
It was specified as a dependency of '@docusaurus/core'

### ISSUE THREAD

**Issue by Dong-Qiu-Long** [cmfcmf/docusaurus-search-local#160]
### Please describe the bug you are seeing

<img width="679" alt="image" src="https://user-images.githubusercontent.com/70185294/212545533-3124e0f5-3954-41b8-8d42-787b30b23506.png">

### Which theme are you using?

Yes, I am using @docusaurus/theme-classic

**Comment by cmfcmf** [comment]
It looks like your Node.js version is too old. I think you need to use at least Node.js 16.
