### ISSUE TITLE
Index title Bar

### ISSUE THREAD

**Issue by EloFran** [cmfcmf/docusaurus-search-local#17]
:unicorn:

hello, how are you?

Would it be possible to index in the searches the heading title of the section where the doc is located?

thx

![image](https://user-images.githubusercontent.com/37640520/95813448-3553e980-0d18-11eb-9ba2-a4d5002ac511.png)

**Comment by cmfcmf** [comment]
Hi!

Thank you for bringing this up - I have released v0.5.0 with a new plugin option `indexDocSidebarParentCategories` that can be used to enable this behavior. Set it to `1` to index the parent category in the sidebar, or to a higher value to also index the parent of the parent category in the sidebar (if it exists).
