### ISSUE TITLE
Missing dependency tslib

### ISSUE THREAD

**Issue by hjellek** [cmfcmf/docusaurus-search-local#192]
### Please describe the bug you are seeing

Installing docusaurus with pnpm (which have stricter defaults to hoisting) causes this plugin to be unable to import `tslib`, as it is not declared as a dependency.

Docusaurus itself correctly specifies this dependency: https://github.com/facebook/docusaurus/blob/3f09fb11a12950c9419ae38fb1b7a04ec1ec8e66/packages/docusaurus/package.json#L98

### Which version of Docusaurus and @cmfcmf/docusaurus-search-local are you using?

Docusaurus 2.4.1
docusaurus-local-search 1.1.0

### Which theme are you using?

Yes, I am using @docusaurus/theme-classic

**Comment by cmfcmf** [comment]
Thank you, both are added now.
