### ISSUE TITLE
Add support for docusaurus v3

### ISSUE THREAD

**Issue by vixducis** [cmfcmf/docusaurus-search-local#194]
The title says it all. The docusaurus v3 beta has been dropped recently, and it promises some nice improvements. Adding support for this new version would be awesome.

**Comment by oawad79** [comment]
yes, please

**Comment by canuto** [comment]
🙏

**Comment by DEVTomatoCake** [comment]
Simply overriding the dependency seems to work.

Add this to your package.json:
```json
"overrides": {
    "@cmfcmf/docusaurus-search-local": {
        "@docusaurus/core": "^3.0.0-rc.0"
    }
}
```

**Comment by SubJunk** [comment]
There is a maintained fork of this repository that supports v3 https://github.com/easyops-cn/docusaurus-search-local
