### ISSUE TITLE
Override the separator

### ISSUE THREAD

**Issue by micael-atos** [cmfcmf/docusaurus-search-local#20]
For now, lunr consider '-' to be a separator. I can't find the string 'foo-bar' in the search. 
It's possible to change the way the index is built by changing the separator: 
```js
lunr.tokenizer.separator = /\s+/;
```
[See lunr's commit here](https://github.com/olivernn/lunr.js/commit/356d25a98c5d67548c9c65799e151cc5b6e524d3)

Could we add an option in the configuration to override this property?

**Comment by cmfcmf** [comment]
Good point! The commit you referenced also was a very helpful read. I added a new plugin option to configure the separator in version 0.5.0 :tada:
