### ISSUE TITLE
Search result path not correct

### ISSUE THREAD

**Issue by h3nkk44** [cmfcmf/docusaurus-search-local#214]
### Please describe the bug you are seeing

Hi,

I installed this plugin to an empty docusaurus project and run all the command without any customization or modifications. When i build and serve the project the search works and shows results fine, but the path where the result is pointing is not working correct.

I dont know if this is a undocumentened config or bug.

![Screenshot 2024-07-05 113950](https://github.com/cmfcmf/docusaurus-search-local/assets/123746320/3c7c4b2f-636f-4f7c-8e7a-123b1c462c32)

As you can see from the image the path is duplicating after the docs part.

"https://symmetrical-space-doodle-x5rrrgx9pq4hv74v-3000.app.github.dev/docs/tutorial-extras/translate-your-site/docs/tutorial-extras/translate-your-site#start-your-localized-site"

When it should be:

"https://symmetrical-space-doodle-x5rrrgx9pq4hv74v-3000.app.github.dev/docs/tutorial-extras/translate-your-site#start-your-localized-site"

Thanks!

### How can we best reproduce the bug?

1. Install docusaurus
2. Install plugin with default settings
3. Test

### Which version of Docusaurus and @cmfcmf/docusaurus-search-local are you using?

Latest  that are available

### Which Node.js version are you using?

22.3.0

### Which theme are you using?

Yes, I am using @docusaurus/theme-classic

### How does your plugin config look like?

Default config

**Comment by sibelius** [comment]
it is duplicating somehow

**Comment by Rob-Purbrick** [comment]
Seeing same behaviour in previously working docs

**Comment by olganaumenko** [comment]
<img width="662" alt="Снимок экрана 2024-07-12 в 12 11 03" src="https://github.com/user-attachments/assets/7761e4bd-257f-41b0-9ec7-a0bad935694d">

I see the same problem for my website :(

**Comment by clainchoupi** [comment]
I have the same problem since a few weeks.

I wonder how that could be related to an incompatibility between Node, Docusaurus and CMFCMFSearchLocal.
In my package-lock.json file I have the following :

`{
      "name": "myDoc",
      "version": "0.0.0",
      "dependencies": {
        "@cmfcmf/docusaurus-search-local": "^0.11.0",
        "@docusaurus/core": "^3.4.0",
        "@docusaurus/preset-classic": "^3.4.0",
        "@docusaurus/theme-mermaid": "^3.4.0",
        "@mdx-js/react": "^3.0.0",
        "clsx": "^1.2.1",
        "prism-react-renderer": "^1.3.5",
        "react": "^18.2.0",
        "react-dom": "^18.2.0",
        "reveal.js": "^5.0.0",
        "swagger-ui-react": "^4.18.1"
      },
      "devDependencies": {
        "@docusaurus/module-type-aliases": "^3.4.0",
        "@tsconfig/docusaurus": "^2.0.2"
      },
      "engines": {
        "node": ">=16.14"
      }
    }
`

CMF and React are locked, but not Node, so there might be something happening here ?

**Comment by fxamauri** [comment]
This https://github.com/cmfcmf/docusaurus-search-local/pull/216 should resolve, can you test applying patch?

```git
diff --git a/node_modules/@cmfcmf/docusaurus-search-local/lib/server/parse.js b/node_modules/@cmfcmf/docusaurus-search-local/lib/server/parse.js
index bf41fa2..50bf040 100644
--- a/node_modules/@cmfcmf/docusaurus-search-local/lib/server/parse.js
+++ b/node_modules/@cmfcmf/docusaurus-search-local/lib/server/parse.js
@@ -109,7 +109,9 @@ function html2text(html, type, url = "?") {
                 // <a class="hash-link" href="#first-header" title="Direct link to heading">#</a>
                 .not("a[aria-hidden=true], a.hash-link")
                 .text();
-            const hash = $(heading).find("a.hash-link").attr("href") || "";
+            const linkHash = $(heading).find("a.hash-link").attr("href") || ""
+            const [, hashPart] = linkHash.split("#")
+            const hash = hashPart ? `#${hashPart}` : "";
             let $sectionElements;
             if ($(heading).parents(".markdown").length === 0) {
                 // $(heading) is the page title

```

**Comment by leandroruel** [comment]
i was taking a look and the duplicated url is already in the generated json file (search-index-docs-default-current.json) from what i can see. see **sectionRoute**. but i'm still taking a look further

```json
{
      "id": 45,
      "pageTitle": "Translate your site",
      "sectionTitle": "Start your localized site",
      "sectionRoute": "/docs/tutorial-extras/translate-your-site/docs/tutorial-extras/translate-your-site#start-your-localized-site",
      "type": "docs"
    },
```

**Comment by leandrucarvalho** [comment]
> Este [problema #216](https://github.com/cmfcmf/docusaurus-search-local/pull/216) deve ser resolvido. Você pode testar a aplicação do patch?
> 
> ```
> diff --git a/node_modules/@cmfcmf/docusaurus-search-local/lib/server/parse.js b/node_modules/@cmfcmf/docusaurus-search-local/lib/server/parse.js
> index bf41fa2..50bf040 100644
> --- a/node_modules/@cmfcmf/docusaurus-search-local/lib/server/parse.js
> +++ b/node_modules/@cmfcmf/docusaurus-search-local/lib/server/parse.js
> @@ -109,7 +109,9 @@ function html2text(html, type, url = "?") {
>                  // <a class="hash-link" href="#first-header" title="Direct link to heading">#</a>
>                  .not("a[aria-hidden=true], a.hash-link")
>                  .text();
> -            const hash = $(heading).find("a.hash-link").attr("href") || "";
> +            const linkHash = $(heading).find("a.hash-link").attr("href") || ""
> +            const [, hashPart] = linkHash.split("#")
> +            const hash = hashPart ? `#${hashPart}` : "";
>              let $sectionElements;
>              if ($(heading).parents(".markdown").length === 0) {
>                  // $(heading) is the page title
> ```
> 
> #### como aplicar o patch?
> 1 - copie o patch acima 2 - Na raiz do seu projeto docsaurus execute o comando:`pbpaste | git apply`
> 
> ou use [patch-package](https://www.npmjs.com/package/patch-package)


I just tried @fxamauri solution and it worked, thanks @fxamauri 

![image](https://github.com/user-attachments/assets/3577fdac-892f-485c-970e-4d746ce5d098)

**Comment by slorber** [comment]
Note: I reverted the Docusaurus v3.4 change to unbreak search plugins in v3.5.

Although you should still apply a fix on your side. See reasons here:
- https://github.com/facebook/docusaurus/pull/10311
- https://github.com/gabrielcsapo/docusaurus-plugin-search-local/issues/82

But v3.5 has another issue, please wait until I publish v3.5.2 with a fix for https://github.com/cmfcmf/docusaurus-search-local/issues/217

**Comment by slorber** [comment]
Docusaurus v3.5.2 has been released and should work fine with this plugin (I tried with v1.2)

---

Note: you may get another error while building your site.

```text
[ERROR] Error: Unable to build website for locale en.
  ...
  [cause]: TypeError: Cannot read properties of undefined (reading 'load')
      at getDocusaurusTag (.../@cmfcmf/docusaurus-search-local/lib/server/parse.js:194:33)
      at .../@cmfcmf/docusaurus-search-local/lib/server/index.js:288:60
```

It is a different issue, related to a recent release of Cheerio v1.0 that did unexpected breaking changes. See my PR for details and workarounds: https://github.com/cmfcmf/docusaurus-search-local/pull/218
