### ISSUE TITLE
Module not found: Can't resolve '@theme/hooks/useDocs'

### ISSUE THREAD

**Issue by shinout** [cmfcmf/docusaurus-search-local#26]
### Bug description 

An error occurred: Module not found: Can't resolve '@theme/hooks/useDocs' after running `yarn build`.

### Reproduction
- yarn add @cmfcmf/docusaurus-search-local
- add plugin settings to `docusaurus.config.js`
- yarn build
 

#### Package Versions
```
yarn list v1.21.1
├─ @cmfcmf/docusaurus-search-local@0.4.0
├─ @docusaurus/core@2.0.0-alpha.55
├─ @docusaurus/mdx-loader@2.0.0-alpha.55
├─ @docusaurus/plugin-content-blog@2.0.0-alpha.55
├─ @docusaurus/plugin-content-docs@2.0.0-alpha.55
├─ @docusaurus/plugin-content-pages@2.0.0-alpha.55
├─ @docusaurus/plugin-google-analytics@2.0.0-alpha.55
├─ @docusaurus/plugin-google-gtag@2.0.0-alpha.55
├─ @docusaurus/plugin-sitemap@2.0.0-alpha.55
├─ @docusaurus/preset-classic@2.0.0-alpha.55
├─ @docusaurus/theme-classic@2.0.0-alpha.55
├─ @docusaurus/theme-search-algolia@2.0.0-alpha.55
├─ @docusaurus/types@2.0.0-alpha.55
└─ @docusaurus/utils@2.0.0-alpha.55
```

#### Node Version
v12.14.0

#### Docusaurus Environment

- Are you using a custom theme?: No
- Paste the plugin config of the local search plugin from your `docusaurus.config.js` file
```
  plugins: [
    [require.resolve("@cmfcmf/docusaurus-search-local") ]],
```

### Additional Information
There seems to be no file like "hooks/useDocs.js" in this repository.
Is the required file external one?

**Comment by cmfcmf** [comment]
Hi @shinout,

This is likely caused by the version of Docusaurus you are using. Please upgrade to at least v2.0.0-alpha66 and let me know if it works!🎄
