### ISSUE TITLE
Allow to set search bar placeholder

### ISSUE THREAD

**Issue by cstffx** [cmfcmf/docusaurus-search-local#29]
It would be great to be able to customize the search bar placeholder. This would allow to display the appropriate word in other languages

**Comment by cmfcmf** [comment]
Hi! This will be fixed by #34, which uses the new i18n capabilties of Docusaurus which allow you to overwrite the placeholder.

**Comment by cmfcmf** [comment]
This feature has now been released as part of https://github.com/cmfcmf/docusaurus-search-local/releases/tag/v0.6.0.
