### ISSUE TITLE
Unable to resolve dependency tree

### ISSUE THREAD

**Issue by BrokenArchon** [cmfcmf/docusaurus-search-local#36]
### Bug description 
Hello, Team!
I try installation but have error: Unable to resolve dependency tree.

### Reproduction

Run: npm install @cmfcmf/docusaurus-search-local

### Environment
Output:
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: docusaurus@0.0.0
npm ERR! Found: @docusaurus/core@2.0.0-beta.0
npm ERR! node_modules/@docusaurus/core
npm ERR!   @docusaurus/core@"2.0.0-beta.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @docusaurus/core@"^2.0.0" from @cmfcmf/docusaurus-search-local@0.6.1
npm ERR! node_modules/@cmfcmf/docusaurus-search-local
npm ERR!   @cmfcmf/docusaurus-search-local@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/..../.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/.../.npm/_logs/2021-05-13T09_10_02_560Z-debug.log

#### Package Versions
docusaurus@0.0.0 /home/..../docusaurus
├── @docusaurus/core@2.0.0-beta.0
└─┬ @docusaurus/preset-classic@2.0.0-beta.0
  ├── @docusaurus/core@2.0.0-beta.0 deduped
  ├─┬ @docusaurus/plugin-content-blog@2.0.0-beta.0
  │ ├── @docusaurus/core@2.0.0-beta.0 deduped
  │ └─┬ @docusaurus/mdx-loader@2.0.0-beta.0
  │   └── @docusaurus/core@2.0.0-beta.0 deduped
  ├─┬ @docusaurus/plugin-content-docs@2.0.0-beta.0
  │ └── @docusaurus/core@2.0.0-beta.0 deduped
  ├─┬ @docusaurus/plugin-content-pages@2.0.0-beta.0
  │ └── @docusaurus/core@2.0.0-beta.0 deduped
  ├─┬ @docusaurus/plugin-debug@2.0.0-beta.0
  │ └── @docusaurus/core@2.0.0-beta.0 deduped
  ├─┬ @docusaurus/plugin-google-analytics@2.0.0-beta.0
  │ └── @docusaurus/core@2.0.0-beta.0 deduped
  ├─┬ @docusaurus/plugin-google-gtag@2.0.0-beta.0
  │ └── @docusaurus/core@2.0.0-beta.0 deduped
  ├─┬ @docusaurus/plugin-sitemap@2.0.0-beta.0
  │ └── @docusaurus/core@2.0.0-beta.0 deduped
  ├─┬ @docusaurus/theme-classic@2.0.0-beta.0
  │ ├── @docusaurus/core@2.0.0-beta.0 deduped
  │ └─┬ @docusaurus/theme-common@2.0.0-beta.0
  │   └── @docusaurus/core@2.0.0-beta.0 deduped
  └─┬ @docusaurus/theme-search-algolia@2.0.0-beta.0
    └── @docusaurus/core@2.0.0-beta.0 deduped

#### Node Version
`node -v`
v16.1.0
`npm -v`
7.11.2

#### Docusaurus Environment

- Are you using a custom theme? NO
- Paste the plugin config of the local search plugin from your `docusaurus.config.js` file
[docusaurus.config.js.txt](https://github.com/cmfcmf/docusaurus-search-local/files/6471511/docusaurus.config.js.txt)

**Comment by cmfcmf** [comment]
Hi, thank you for your bug report.
Your problem should be fixed in version 0.6.2 of this plugin. Please try it out and let me know if it works!

**Comment by BrokenArchon** [comment]
Yap! You are fixed this! Thank you :)
