### ISSUE TITLE
Indexing contains navigation buttons

### ISSUE THREAD

**Issue by dodocloud** [cmfcmf/docusaurus-search-local#4]
Hello,

we've discovered that search results include labels on `Previous` / `Next` buttons. For instance, in the demo example here: https://christianflach.de/OpenWeatherMap-PHP-API/docs/getting-started , if I search for `API Key`, it will navigate me to the very bottom where the `Next` button is located. Is it possible to either remove it from the indexing algorithm or make it at least configurable, so that labels on those buttons won't appear in the result?

Many thanks

**Comment by cmfcmf** [comment]
Whoopsie! I'll look into it and will likely switch to Cheerio for HTML parsing. I'll see if I can make it configurable as well. Of course I'll aim for the default to be compatible with the default theme. 👍

**Comment by dodocloud** [comment]
That would be super cool :-) many thanks for your effort.

**Comment by cmfcmf** [comment]
Fixed in https://github.com/cmfcmf/docusaurus-search-local/compare/0e64aa7385a0680f5f378c77130d1c103e894e02...88f3ca8986c96bbc4dd0a3c6f29737fc58ca902c. It was surprisingly more work than expected :relieved: 
I'll release 0.1.0 with this fix after looking into #3.

**Comment by dodocloud** [comment]
Amazing! Many thanks! I didn't expect it would be resolved so quickly.
