### ISSUE TITLE
Plugin not compatible with Docusaurus 2.0.0-Beta.7

### ISSUE THREAD

**Issue by yobyot** [cmfcmf/docusaurus-search-local#64]
### Bug description 

This plugin is incompatible with Docusaurus 2.0.0-Beta.7. Please see [this issue](https://github.com/facebook/docusaurus/issues/5716). Thanks.

### Reproduction

*If possible, provide a link to the source of your documentation or at least
the document/page this issue is about (if applicable). If this bug report is 
about a failure that occurs while building your documentation, please find out 
which document breaks the build process by building your documentation with debug
information enabled as described in the README (`DEBUG=1 yarn build`). If you can, 
provide the document that breaks the build process as indicated by the debug messages.*

#### Package Versions
If you use Yarn: 
`yarn list --pattern '@docusaurus|@cmfcmf' --depth=0`
If you use npm: 
`npm list '@docusaurus/core' '@cmfcmf/docusaurus-search-local'`

#### Node Version
`node -v`

#### Docusaurus Environment

- Are you using a custom theme?
- Paste the plugin config of the local search plugin from your `docusaurus.config.js` file

**Comment by cmfcmf** [comment]
Thank you for bringing this up! I released the fix proposed in #65 in 0.6.7.

**Comment by yobyot** [comment]
And _thank you_ @cmfcmf and @Josh-Cena for being right on top of the issue and spending the time and effort to fix it right away. End users cannot ask for more.
