### ISSUE TITLE
Request: Support more than one docs plugin

### ISSUE THREAD

**Issue by 0xGizmo** [cmfcmf/docusaurus-search-local#70]
I am building a docs site and we have three instances of `@docusaurus/plugin-content-docs`. Each have their own unique ID.

Unfortuantely `docusuaurus-search-local` doesn't support multiple `plugin-content-docs` instances and enforces indexing of the `default` ID.

Please add support for multiple instances of `plugin-content-docs`.

**Comment by cmfcmf** [comment]
Closing as a duplicate of #33.

**Comment by cmfcmf** [comment]
Implemented in 0.8.0.
