### ISSUE TITLE
search icon not showing

### ISSUE THREAD

**Issue by code-masala** [cmfcmf/docusaurus-search-local#71]
in docusaurus.config.js
`plugins: [require.resolve("@easyops-cn/docusaurus-search-local")]`

in package.json

```
 "@cmfcmf/docusaurus-search-local": "^0.6.6",
 "@easyops-cn/docusaurus-search-local": "^0.19.1",
```
what else i have to add plz help

**Comment by cmfcmf** [comment]
It looks like you are using a different plugin (`"@easyops-cn/docusaurus-search-local"`).
