### ISSUE TITLE
[Feature Request] Search highlight

### ISSUE THREAD

**Issue by l0nax** [cmfcmf/docusaurus-search-local#9]
First of all: Thanks for this plugin! I really appreciate that you've written this plugin because it gives us the possibility to have a search bar in our internal docs without using Algolia. Thanks, man :+1:

#### Description

Would it be possible to add an option that allows the user to enable/ disable highlight of the search results on the (target) page?

#### Proposal

[mark.js](https://markjs.io/) seems to have a good and Open Source (licensed [under MIT](https://github.com/julmot/mark.js/blob/master/LICENSE)) library that can be easily integrated into this library.

**Comment by cmfcmf** [comment]
Hi @l0nax!
Great idea! I implemented highlighting in 707aa11 and released version 0.2.0. :tada:
