### ISSUE TITLE
[Bug] Error: Can't resolve '@theme/hooks/useDocs'

### ISSUE THREAD

**Issue by homotechsual** [cmfcmf/docusaurus-search-local#93]
### Please describe the bug you are seeing

Can't build with canary using this plugin. Looks like useDocs has been replaced by `@docusaurus/plugin-content-docs/client`.

https://github.com/facebook/docusaurus/pull/6287

### Which version of Docusaurus and @cmfcmf/docusaurus-search-local are you using?

@cmfcmf/docusaurus-search-local@0.9.4
@docusaurus/core@0.0.0-4470

### Which Node.js version are you using?

v16.13.2

### Which theme are you using?

Yes, I am using @docusaurus/theme-classic

### How does your plugin config look like?

require.resolve("@cmfcmf/docusaurus-search-local"),
      {
        indexDocs: true,
        indexBlog: false,
        indexPages: true,
        language: "en"
      }

**Comment by pklaschka** [comment]
I can confirm this. It breaks when updating `@docusaurus/preset-classic` from `2.0.0-beta.14` to `2.0.0-beta.15`.

According to their changelog, the hooks were moved from `@theme/hooks` to `@docusaurus/theme-common`: https://github.com/facebook/docusaurus/pull/6289

**Comment by edumaciel10** [comment]
I am getting the same error here

**Comment by slorber** [comment]
Hi

This hook is considered an internal API, can you explain how it is used?

**Comment by cmfcmf** [comment]
> This hook is considered an internal API, can you explain how it is used?

The use of this hook was a remnant of when `useContextualSearchFilters` was not yet available in `@docusaurus/theme-common`. I now dropped support for older Docusaurus versions and removed the use of these internal APIs.

> Are there other internal apis that you are using?

I am not 100% sure :) It definitely feels like I am using less and less internal APIs with each new beta of Docusaurus.

**Comment by cmfcmf** [comment]
Fixed in v0.10.0.

**Comment by pklaschka** [comment]
@cmfcmf Thank you for the quick fix!

**Comment by slorber** [comment]
great, thanks :) 

Let me know if you have a use-case for another internal API in the future
